const projects = [
    {
      no : 7,
      name: "Road Rehabilitation Works at Americana Avenue, La Horquette Road",
      status: 'completed',
      location: { lat: 10.6871944, lng: -61.5725556  },
      link: 'AXatkU6KGRs',
    }, 
    {
        no : 8,
        name: "Road Rehabilitation Works at Big Yard, Carenage, Trinidad",
        status: 'completed',
        location: { lat: 10.6828056, lng: -61.5783056  },
        link: 'u-2mo09t1n8',
    },
    {
        no : 9,
        name: "Road Rehabilitation Works at L'Anse Mitan, Carenage, Trinidad",
        status: 'completed',
        location: { lat: 10.6891944, lng: -61.5806944  },
        link: 'xnEEmG50Ctk',
    },
    {
        no : 10,
        name: "Road Rehabilitation Works at La Sanora Park, Carenage, Trinidad",
        status: 'completed',
        location: { lat: 10.682975, lng: -61.57513  },
        link: 'vdVhDB1mqhA',
    },
    {
        no : 11,
        name: "Road Rehabilitation Works at Neckles Drive, Carenage, Trinidad",
        status: 'completed',
        location: { lat: 10.691645, lng: -61.595195  },
        link: 'S6S4tco21Zk',
    },
    {
        no : 12,
        name: "Road Rehabilitation Works at School Street, Carenage, Trinidad",
        status: 'completed',
        location: { lat: 10.6855, lng: -61.59125  },
        link: 'sv3bBN0ro8o',
    },
    {
        no : 13,
        name: "Road Rehabilitation Works at Sea View, Carenage, Trinidad",
        status: 'completed',
        location: { lat: 10.688775, lng: -61.597163  },
        link: 'gw_yhl-4Grg',
    },
    {
        no : 14,
        name: "Road Rehabilitation Works at Upper Abbe Poujade Street, Carenage, Trinidad",
        status: 'completed',
        location: { lat: 10.6921944, lng: -61.5934167  },
        link: '62ZAs-8F2GA',
    },
    {
        no : 17,
        name: "Road Rehabilitation Works at Ali Trace, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.7133889, lng: -61.5688056  },
        link: 'BSC5GfoHlW0',
    },
    {
        no : 18,
        name: "Road Rehabilitation Works at Broome Street, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.6904167, lng: -61.5589167  },
        link: '0Osyeu5uzUw',
    },
    {
        no : 19,
        name: "Road Rehabilitation Works at Farm Road, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.7129444, lng: -61.5666944  },
        link: 'kCge2IypaSo',
    },
    {
        no : 20,
        name: "Drainage and Road Upgrade Works at Goodwood Gardens, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.687785, lng: -61.558506  },
        link: 'K49ScJhZHS8',
    },
    {
        no : 21,
        name: "Road Rehabilitation Works at Hassanali Trace, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.7132778, lng: -61.5676944 },
        link: '_mL283MKlNY',
    },
    {
        no : 22,
        name: "Road Rehabilitation Works at Julien Park, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.7136944, lng: -61.5623056 },
        link: '99NspOzZklE',
    },
    {
        no : 23,
        name: "Drainage and Road Upgrade Works at Sargangar Trace, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.6905556, lng: -61.5616944 },
        link: 'wQtNAo5YGoI',
    },
    {
        no : 24,
        name: "Road Rehabilitation Works at Upper Factory Road, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.7164167, lng: -61.5677778 },
        link: 'p--EPHhQxtg',
    },
    {
        no : 25,
        name: "Drainage and Road Upgrade Works at La Puerta Avenue & Senior Street, Diego Martin, Trinidad",
        status: 'completed',
        location: { lat: 10.6924167, lng: -61.5556667 },
        link: 'DC9DI9VGJgc',
    },
    {
        no : 27,
        name: "Road Rehabilitation Works at Ellis Street, Marabella, Trinidad",
        status: 'scheduled',
        location: { lat: 10.6924167, lng: -61.5556667 },
        link: 'BxyzB-zvP3g',
    },
    {
        no : 28,
        name: "Road Rehabilitation Works at La Borde Lane, Marabella, Trinidad",
        status: 'scheduled',
        location: { lat: 10.2974722, lng: -61.4558333 },
        link: 'BOxKRCVdXog',
    },
    {
        no : 29,
        name: "Road Rehabilitation Works at Riverside Road, Marabella, Trinidad",
        status: 'scheduled',
        location: { lat: 10.3025334, lng: -61.4531164 },
        link: 'zw_nhjn6iZ4',
    },
    {
        no : 31,
        name: "Road Rehabilitation Works at Gomez Trace, St. Mary's Village, Moruga, Trinidad",
        status: 'completed',
        location: { lat: 10.216338, lng: -61.313583 },
        link: 'S82gAeUMCeA',
    },
    {
        no : 32,
        name: "Road Rehabilitation Works at Gomez Trace, St. Mary's Village, Moruga, Trinidad",
        status: 'completed',
        location: { lat: 10.216338, lng: -61.313583 },
        link: 'S82gAeUMCeA',
    },
    {
        no : 33,
        name: "Road Rehabilitation Works at Victoria Avenue, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.663458, lng: -61.518447 },
        link: 'JklMwo6OkwQ',
    },
    {
        no : 34,
        name: "Road Rehabilitation Works at Ariapita Avenue, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.658014, lng: -61.514594 },
        link: 'PxOqP9h1lwo',
    },
    {
        no : 35,
        name: "Road Rehabilitation Works at Tragarete Road, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.657003, lng: -61.519617 },
        link: 'KlO6i9vQqwE',
    },
    {
        no : 36,
        name: "Road Rehabilitation Works at Duke Street, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.655023, lng: -61.510022 },
        link: 'ZsPqU9g6TxY',
    },
    {
        no : 37,
        name: "Road Rehabilitation Works at Independence Square, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.648124, lng: -61.514394 },
        link: 'RjwP7l0yOxE',
    },
    {
        no : 38,
        name: "Road Rehabilitation Works at Park Street, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.658723, lng: -61.507844 },
        link: 'UkP8r9sLw6Q',
    },
    {
        no : 39,
        name: "Road Rehabilitation Works at Charlotte Street, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.652416, lng: -61.511884 },
        link: 'YpQp8o6Uw9E',
    },
    {
        no : 40,
        name: "Road Rehabilitation Works at Henry Street, Port of Spain, Trinidad",
        status: 'completed',
        location: { lat: 10.655733, lng: -61.512394 },
        link: 'QqQp7o4Tt1R',
    }
    // Add more projects here as needed
  ];

  export default projects;
